const MIN_CREDITS_FULL_TIME = 12;
const MAX_CREDITS_STANDARD = 18;
const MAX_CREDITS_PROBATION = 14;
const MAX_CREDITS_OVERLOAD_CAP = 21;

module.exports = {
  MIN_CREDITS_FULL_TIME,
  MAX_CREDITS_STANDARD,
  MAX_CREDITS_PROBATION,
  MAX_CREDITS_OVERLOAD_CAP,
};
